In [1]:
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import numpy as np

We import raw wb data and import data into multiple csv files for different years for simplification of flow later on model building and testing.

In [2]:
df = pd.read_csv("Raw_WB_Data.csv")
df.head()

,Country Name,Country Code,Series Name,Series Code,2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019]
0,Afghanistan,AFG,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.ZS,26.1,27.6,28.8,30.3,31.4,32.6
1,Afghanistan,AFG,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.RU.ZS,10.2,11.4,12.6,13.5,14.5,15.6
2,Afghanistan,AFG,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.UR.ZS,78,79.5,80.5,81.6,82.6,83.2
3,Afghanistan,AFG,Access to electricity (% of population),EG.ELC.ACCS.ZS,89.5,71.5,97.7,97.7,93.4,97.7
4,Afghanistan,AFG,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,86.5,64.6,97.1,97.1,91.6,97.1

In [3]:
def split_pivot(df, year):
    """
    Transforms the dataset by pivoting it for a specific year, 
    filtering out global/regional entries, and removing columns with excessive missing values.

    Args:
        df (pd.DataFrame): The input DataFrame containing data for multiple years and indicators.
        year (str): The target year to extract and pivot data (e.g., "2020").

    Returns:
        pd.DataFrame: A transformed DataFrame with countries as rows, series codes as columns, 
                      and data for the specified year.
    """
    # Construct the column name for the specified year (e.g., "2020 [YR2020]")
    ystring = f"{year} [YR{year}]"
    
    # Replace non-numeric entries ("..") with NaN and convert the column to float
    df[ystring] = df[ystring].replace("..", None).astype(float)
    
    # Pivot the DataFrame to have countries as rows and series codes as columns
    df_trans = pd.pivot_table(df, values=ystring, index="Country Name", columns="Series Code", sort=False)
    
    # Remove the last 48 rows, assuming these are global or regional entries rather than individual countries
    df_trans = df_trans.iloc[:-48]
    
    # Determine columns with more than 40% missing values
    drop_col_threshold = int(0.4 * len(df_trans))
    drop_cols = df_trans.columns[df_trans.isnull().sum() > drop_col_threshold]
    
    # Drop columns with excessive missing values
    df_trans.drop(columns=drop_cols, inplace=True)
    
    return df_trans

In [5]:
df_trans=split_pivot(df,"2017")

#Replacing missing values with median and exporting to a file with year name for simpler loading
df_trans = df_trans.fillna(df_trans.median())
df_trans.to_csv('data_2017.csv',index=True)

In [6]:
#Saving the remaining feature names and their short description
unique_cols = df['Series Name'].nunique()
data_dict = df[['Series Code', 'Series Name']][:unique_cols]
data_dict.to_csv('Feature_codes_description.csv', index=True)